# Generated by Django 4.1.7 on 2023-03-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='load',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
